se_bubuchacha/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

urls.py
from django.views.generic import TemplateView
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path("", views.CarpoolListView.as_view(), name="index"),
    path(
        "student/signup_and_login",
        views.StudentSignUpAndLoginView.as_view(),
        name="signup_and_login_student",
    ),
    path(
        "driver/signup_and_login",
        views.DriverSignUpAndLoginView.as_view(),
        name="signup_and_login_driver",
    ),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path(
        "password_change/",
        views.MyPasswordChangeView.as_view(),
        name="password_change",
    ),
    path("aboutus/", views.aboutus_view, name="aboutus"),
    path("carpools/", views.CarpoolListView.as_view(), name="carpools"),
    path("carpool_list_region/", views.carpool_list_region, name="carpools_region"),
    path(
        "carpool/history/",
        views.CarpoolHistoryListView.as_view(),
        name="carpool_history",
    ),
    path("carpool/create/", views.carpool_create, name="carpool_create"),
    path("carpool/<int:pk>", views.CarpoolDetailView.as_view(), name="carpool-detail"),
    path(
        "carpool/change_status/<int:pk>",
        views.carpool_change_status_view,
        name="carpool_change_status",
    ),
    path(
        "carpool/update_status/<int:pk>",
        views.carpool_update_status_view,
        name="carpool_update_status",
    ),
    path("price/", views.PriceView.as_view(), name="price"),
    path("drivers/", views.DriverListView.as_view(), name="drivers"),
    path("driver/<int:pk>", views.DriverReviewView.as_view(), name="driver_detail"),
    path("comment/delete/<int:pk>", views.delete_comment_view, name="delete_comment"),
    path("comment/edit/<int:pk>", views.edit_comment_view, name="edit_comment"),
    path("comment/create/", views.CommentCreateView.as_view(), name="comment_create"),
    path(
        "nothing/",
        TemplateView.as_view(template_name="app/nothing.html"),
        name="nothing",
    ),
]

models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
import datetime
from django.utils.timezone import now
from django.core.exceptions import ObjectDoesNotExist


class User(AbstractUser):
    class Types(models.TextChoices):
        STUDENT = "STUDENT", "Student"
        DRIVER = "DRIVER", "Driver"
        NONE = "NONE", "None"

    # 使用者類型：學生 or 司機
    type = models.CharField(
        max_length=50,
        choices=Types.choices,
        default=Types.NONE,
        verbose_name="user type",
    )

    def is_student(self):
        return self.type == self.Types.STUDENT

    def is_driver(self):
        return self.type == self.Types.DRIVER

    def to_student(self):
        try:
            return Student.objects.get(pk=self.pk)
        except ObjectDoesNotExist:
            return None

    def to_driver(self):
        try:
            return Driver.objects.get(pk=self.pk)
        except ObjectDoesNotExist:
            return None

    @property
    def current_carpool(self):
        if self.is_student():
            return (
                self.to_student()
                .student_carpools.filter(status="w")
                .order_by("date")
                .first()
            )
        elif self.is_driver():
            return self.to_driver().driver_carpools.filter(status="w").last()

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})


class StudentManager(UserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.STUDENT)


class DriverManager(UserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.DRIVER)


class Student(User):
    objects = StudentManager()

    class Meta:
        proxy = True

    def __str__(self):
        """String for representing the Student object."""
        return self.username


class Driver(User):
    objects = DriverManager()

    class Meta:
        proxy = True

    @property
    def score(self):
        # from Comment model "related_name"
        score = self.driver_comments.aggregate(models.Avg("score")).get("score__avg")
        if score:
            return round(score)
        else:
            return None


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # 性別，預設為男性
    class SexTypes(models.TextChoices):
        MALE = "MALE", "生理男"
        FEMALE = "FEMALE", "生理女"

    base_type = SexTypes.MALE
    sex = models.CharField(
        max_length=10, choices=SexTypes.choices, default=base_type, verbose_name="sex"
    )
    # 姓名
    name = models.CharField(max_length=8, verbose_name="name")
    # 手機號碼
    phone_num = models.CharField(
        max_length=10,
        validators=[RegexValidator(regex=r"^09\d{8}$", message="手機號碼格式輸入錯誤！")],
        verbose_name="phone number",
    )

    """ Driver Only """
    # 隸屬公司
    company = models.CharField(max_length=25, blank=True, verbose_name="company")
    # 執業登記證號
    cert_code = models.CharField(
        max_length=7,
        blank=True,
        validators=[
            RegexValidator(
                regex=r"^(?=.{7}$)[a-zA-Z]{1,}\d{1,}$", message="登記證證號格式輸入錯誤！"
            )
        ],
        verbose_name="certificate code",
    )
    # 執業登記證號到期日
    cert_expirydate = models.DateField(
        null=True, blank=True, verbose_name="certificate expiration date"
    )


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created and not hasattr(instance, "profile"):
        Profile.objects.create(user=instance)
    instance.profile.save()


class Car(models.Model):
    capacity = models.IntegerField(
        default=3,
        validators=[MaxValueValidator(9), MinValueValidator(3)],
        verbose_name="car capacity",
    )
    plate = models.CharField(
        max_length=8,
        verbose_name="car plate number",
        validators=[RegexValidator(regex=r"^[A-Z]{3}\-\d{4}$", message="車牌號碼格式輸入錯誤！")],
    )

    UTILITY_CHOICES = (
        ("n", "一般轎車"),  # 1
        ("e", "環保電動車"),  # 0.9
        ("l", "豪華轎車"),  # 1.5
        ("a", "無障礙汽車"),  # 1
    )

    type = models.CharField(
        max_length=1,
        choices=UTILITY_CHOICES,
        default="n",
        verbose_name="car utility type",
    )

    # relations one to one
    driver = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=False)

    class Meta:
        ordering = ["type", "capacity"]


class Place(models.Model):
    """Model representing a place"""

    # 地點名稱
    name = models.CharField(
        max_length=50,
        verbose_name="place name",
    )

    def __str__(self):
        """String for representing the Place object."""
        return self.name


class Comment(models.Model):
    """Model representing a comment"""

    time = models.DateTimeField(
        default=now, help_text="Enter a time you want to take a car"
    )
    content = models.TextField()
    score = models.IntegerField(validators=[MaxValueValidator(5), MinValueValidator(1)])

    # relations many to one
    critic = models.ForeignKey(
        Student, on_delete=models.SET_NULL, null=True, related_name="student_comments"
    )
    criticed = models.ForeignKey(
        Driver, on_delete=models.SET_NULL, null=True, related_name="driver_comments"
    )

    def __str__(self):
        """String for representing the Comment object."""
        return self.content


class Carfare(models.Model):
    """Model representing a carfare"""

    # relations many to one
    # 出發地
    departure = models.ForeignKey(
        Place,
        on_delete=models.SET_NULL,
        null=True,
        related_name="departure_fares",
        verbose_name="departure",
    )
    # 目的地
    arrival = models.ForeignKey(
        Place,
        on_delete=models.SET_NULL,
        null=True,
        related_name="arrival_fares",
        verbose_name="arrival",
    )

    # 車資
    fare = models.PositiveIntegerField(verbose_name="fare")

    class Meta:
        ordering = ["departure", "arrival"]

    def __str__(self):
        """String for representing the Place object."""
        return f"{self.departure} -> {self.arrival}: {self.fare}"


class Carpool(models.Model):
    """Model representing a carpool."""

    date = models.DateField(default="2022-12-21")
    time = models.TimeField(default="21:24")

    carfare = models.ForeignKey(Carfare, on_delete=models.SET_NULL, null=True)
    lower_passengers = models.IntegerField()

    # relations many to one
    driver = models.ForeignKey(
        Driver,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="driver_carpools",
    )

    # relations many to many
    passengers = models.ManyToManyField(
        Student, related_name="student_carpools", blank=True
    )

    STATUS_CHOICES = (
        ("w", "Waiting"),
        ("d", "Driving"),
        ("a", "Arrived"),
    )

    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default="w")

    class Meta:
        ordering = ["date", "time"]

    @property
    def departure(self):
        return self.carfare.departure.name

    @property
    def arrival(self):
        return self.carfare.arrival.name

    @property
    def fare(self):
        return self.carfare.fare

    @property
    def has_vacancy(self):
        if not self.driver:
            return True
        return self.driver.car.capacity > self.passengers.count()

    @property
    def has_driver(self):
        if self.driver:
            return True
        else:
            return False

    # def is_overdue(self):
    #     if self.time >= datetime.datetime.today():
    #         return False
    #     return True

    @property
    def avg_fare(self):
        total_passengers = self.passengers.count()
        if total_passengers == 0:
            return None
        return round(self.carfare.fare / self.passengers.count())

    def is_student_in(self, student):
        if student is None:
            return False
        try:
            self.passengers.get(username=student.username)
            return True
        except ObjectDoesNotExist:
            return False

    def is_driver_in(self, driver):
        return self.driver == driver

    def is_user_in(self, user):
        if user and user.is_student():
            return self.is_student_in(user)
        else:
            return self.is_driver_in(user)

    def __str__(self):
        """String for representing the Carpool object."""
        return f"s: {self.status} {self.time}, {self.departure} to {self.arrival}"

    def get_absolute_url(self):
        """Returns the url to access a detail record for this carpool."""
        return reverse("app:carpool-detail", args=[str(self.id)])

templates/app/aboutus.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <div class="row" style="padding-top: 100px;height: 100%;width:100%;">
        <div class="col" style="background-color:#FBF0D8;text-align:center;">
            <img src="{% static 'image/logo.png' %}" alt="" style="padding-top: 200px">
        </div>
        <div class="col">
            <h1 style="text-align: center;padding-top: 180px;">About BUBUCHACHA</h1>
            <p style="padding: 10px 168px;font-size: 20px;line-height: 2;">
                我們是BUBUCHACHA開發團隊
                <br>
                希望大家會喜歡我們的共乘平台
                <br>
                從現在開始享受愉快的共乘體驗吧!
                <br>
                BTW : 祝大家期末都all pass! 新年快樂!
            </p>
        </div>
    </div>
{% endblock %}

templates/app/carpool_detail.html
<div id="main" hx-swap-oob="true">
{% extends "base.html" %}
{% block content %}

{% load static %}
<script src="{% static 'js/index.js' %}"></script>
<script>
  document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })
</script>

<body style="padding-top: 120px;">

<div class="container pt-2">
  <div class="row">
    <div class="col-sm-3 border-end">
      <h2 class="text-center">司機資訊</h2>
      <p size="1h-10"></p>
        <img src="{% static 'image/driver.png' %}" width="100" style="display:block; margin:auto;" /> 
        <p size="1h-10"></p>
        <dl class="row">
          <dt class="col-sm-4 text-center"><h6><b>司機</b></h6></dt>
          {% if carpool.driver %} {{ carpool.driver }} 
          {% else %} 暫無司機 
          {% endif %}
          <!-- <dd class="col-sm-5 text-center"><h6>賴承緒</h6></dd> -->
        </dl>
        <dl class="row">
          <dt class="col-sm-4 text-center"><h6><b>電話</b></h6></dt>{{ carpool.driver.profile.phone_num }}
          <!-- <dd class="col-sm-5 text-center"><h6>0970400322</h6></dd> -->
        </dl>
        <dl class="row">
          <dt class="col-sm-4 text-center"><h6><b>車牌</b></h6></dt>{{ carpool.driver.car.plate }}

        </dl>
        <dl class="row">
          <dt class="col-sm-4 text-center" ><h6><b>評價</b></h6></dt>
          <dt class="col-sm-8"  >
          <span class="yellow_star" >
            {% for _ in ""|rjust:5 %}
                        {% if forloop.counter0 < carpool.driver.score %}
                            <!-- 滿星星 -->
                            <svg xmlns="http://www.w3.org/2000/svg"
                                 width="16"
                                 height="16"
                                 fill="currentColor"
                                 class="bi bi-star-fill"
                                 viewBox="0 0 16 16">
                                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                            </svg>
                        {% else %}
                            <!-- 空星星 -->
                            <svg xmlns="http://www.w3.org/2000/svg"
                                 width="16"
                                 height="16"
                                 fill="currentColor"
                                 class="bi bi-star"
                                 viewBox="0 0 16 16">
                                <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                            </svg>
                        {% endif %}
                    {% endfor %}
          </span>
        </dt>
      </dl>

      {% if carpool.driver.username == user.username %}
        <div class="text-center" id="carpool-change-status">
          {% if carpool.status == 'w' %}
            <button hx-patch="{% url 'app:carpool_change_status' pk=carpool.pk %}"
                    hx-target="#carpool-change-status"
                    hx-swap="innerHTMl"
                    class="btn btn-outline-dark"
                    style="width:180px">出發</button>
          {% elif carpool.status == 'd' %}
            <button hx-patch="{% url 'app:carpool_change_status' pk=carpool.pk %}"
                    hx-target="#carpool-change-status"
                    hx-swap="innerHTMl"
                    class="btn btn-outline-dark"
                    style="width:180px">抵達</button>
          {% else %}
            <button disabled
                    class="btn btn-outline-dark"
                    style="width:180px">已抵達</button>
          {% endif %}
        </div>
      {% endif %}

  </div>
  <div class="col-sm-9">
    <div class="container">

      {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong> 
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
      </ul>
      {% endif %}

      <dl class="row">
        <dt class="col-sm-6 text-center"><h1>{{ carpool.departure }}</h1></dt>
        <dt class="col-sm-1 text-center"><h1>➜</h1></dt>
        <dd class="col-sm-5 text-center"><h1>{{ carpool.arrival }}</h1></dd>
      </dl>
      <hr style="border:0.5px solid #CFCFCF;"/>
      <!-- 時間 -->
        <div class="row m-3 p-3 border shadow rounded">
          <div class="col-sm-1"></div>
          <div class="col-sm-2 text-center">
            <img src="{% static 'image/clock.png' %}" style='width:50px;'>
          </div>
          <div class="col-sm-3 text-center align-self-center">
            <h4>出發時間</h4>
          </div>
          <div class="col-sm-5 text-center align-self-center">
            <h4><b>{{ carpool.date|date:'Y-m-d' }}</b>  &nbsp; [{{ carpool.time|time:"H:i" }}] </h4>
          </div>
        <div class="col-sm-1"></div>
      </div>
      <!-- 乘客列表 -->
      <div class="row m-3 p-3 border shadow rounded">
        <div class="col-sm-1"></div>
        <div class="col-sm-2 text-center">
          <img src="{% static 'image/passenger.png' %}" style='width:50px;'>
        </div>
        <div class="col-sm-3 text-center align-self-center">
          <h4>乘客列表</h4>
        </div>
        <div class="col-sm-5 text-center align-self-center">
          <h4><b>
            {% for student in carpool.passengers.all %}
              {{ student }}
              {% if forloop.counter < carpool.passengers.count %}
                、
              {% endif %}
            {% endfor %}
          </b></h4>
        </div>
      </div>
    <div class="col-sm-1"></div>
    <!-- 平均每人價格 -->
    <div class="row m-3 p-3 border shadow rounded">
      <div class="col-sm-1"></div>
      <div class="col-sm-2 text-center">
        <img src="{% static 'image/money.png' %}" style='width:50px;'>
      </div>
      <div class="col-sm-3 text-center align-self-center">
        <h4>平均價格</h4>
      </div>
      <div class="col-sm-5 text-center align-self-center">
        <h4><b>{{ carpool.avg_fare }}</b></h4>
      </div>
    <div class="col-sm-1">
    </div>
    </div>
    
    <form action="" method="post">
      {% csrf_token %}
      {% comment %} <button type="submit" class="btn btn-outline-danger rounded-pill position-absolute end-0 translate-middle-x"><b>+</b></button> {% endcomment %}
      {% if user.is_authenticated %}
        <button type="submit" name="leave" class="btn btn-outline-secondary position-absolute translate-middle-x"><b>退出</b></button>
        <button type="submit" name="join" class="btn btn-outline-danger position-absolute end-0 translate-middle-x"><b>加入</b></button>

      {% endif %}
    </form>

    <div hx-get="{% url 'app:carpool_update_status' pk=carpool.pk %}" hx-trigger="load, every 1s" style="display: none"></div>
</div>
{% endblock %}
</div>

 

templates/app/carpool_list.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
    {% load widget_tweaks %}
    <link rel="stylesheet" href="{% static 'css/star.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.2.min.js"
            integrity="sha256-2krYZKh//PcchRtd+H+VyyQoZ/e3EcrkxhM8ycwASPA="
            crossorigin="anonymous"></script>
    <script src="https://unpkg.com/gijgo@1.9.14/js/gijgo.min.js"
            type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.14/css/gijgo.min.css"
          rel="stylesheet"
          type="text/css"/>
    <script src="{% static 'js/index.js' %}"></script>
    <script src="{% static 'js/group_new.js' %}"></script>
    <body style="padding-top: 120px;padding-bottom: 50px;">
        {% if user.is_student %}
        <button type="button"
                hx-get="{% url "app:carpool_create" %}"
                hx-target="#dialog"
                class="btn btn-outline-danger rounded-pill newgroup"
                data-bs-toggle="modal"
                data-bs-target="#exampleModal"
                style="width:70px;height:70px;font-size:30px;">
            +
        </button>
        {% endif %}
        <div id="modal"
             class="modal fade"
             tabindex="-1"
             aria-labelledby="exampleModalLabel">
            <div id="dialog" class="modal-dialog" hx-target="this"></div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-3 border-end">
                    <h2 class="text-center">
                        共乘團篩選
                    </h1>
                    <form hx-get="{% url 'app:carpools_region' %}" hx-target="#filter-target">
                        <div class="form-group">
                            <label for="date">日期選擇</label>
                            {% render_field form.date class="form-control id-form-date" %}
                        </div>
                        <div class="form-group">
                            <label for="time">時間選擇</label>
                            {% render_field form.time class="form-control id-form-time" %}
                        </div>
                        <div class="form-group">
                            <label for="carfare">出發地和目的地</label>
                            {% render_field form.carfare class="form-control" %}
                        </div>
                        <div class="form-group">
                            <label for="already_in">目前已加入人數</label>
                            {% render_field form.already_in class="form-control" %}
                        </div>
                        <div class="form-group form-check">
                            {% render_field form.has_driver class="form-check-input" %}
                            <label class="form-check-label" for="{{ form.has_driver.id_for_label }}">已有司機承接</label>
                        </div>
                        <div class="form-group form-check">
                            {% render_field form.has_vacancy class="form-check-input" %}
                            <label class="form-check-label" for="{{ form.has_vacancy.id_for_label }}">尚有空位</label>
                        </div>
                        <div class="pt-3">
                            <button type="submit" class="form-control btn btn-outline-dark" class='sure'>確定</button>
                        </div>
                    </form>
                    {% if user.is_authenticated %}
                        <hr/>
                        <button hx-get="{% url 'app:carpools_region' %}?filter_is_user_in=True" hx-target="#filter-target" class="form-control btn btn-outline-danger" class='sure'>顯示已加入之共乘團</button>
                    {% endif %}
                </div>
                <!-- carpool-->
                <div class="col-sm-9">
                    <div class="container">
                        <div class="row"
                             id="filter-target"
                             hx-get="{% url "app:carpools_region" %}"
                             hx-trigger="load, carpoolListChanged from:body">
                        </div>
                    </div>
                </div>
                <script src="{% static 'js/dialog.js' %}"></script>
            {% endblock %}

templates/app/driver_list.html
{% extends "base.html" %}
{% block title %}司機列表{% endblock %}
{% load static %}
{% block content %}
    <div style="padding-top: 120px;">
        <div class="container mt-5">
            {% if driver_list %}
                <h3 class="text-center">
                    <b>司機列表</b>
                </h3>
                {% for driver in driver_list %}
                    <a href="{% url 'app:driver_detail' driver.pk %}"
                       class="row m-3 p-3 border shadow rounded">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-2 text-center">
                            <img src="{% static 'image/taxi.png' %}" alt="" style='width:50px;'>
                        </div>
                        <div class="col-sm-3 text-center align-self-center">
                            <h5>
                                <b>
                                    {{ driver.profile.name }}
                                </b>
                            </h5>
                        </div>
                        {% if driver.score is None %}
                            <div class="col-sm-5 align-self-center">暫無評論</div>
                        {% else %}
                            <div class="col-sm-5 yellow_star align-self-center">
                                {% for _ in ""|rjust:5 %}
                                    {% if forloop.counter0 < driver.score %}
                                        <!-- 滿星星 -->
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             width="16"
                                             height="16"
                                             fill="currentColor"
                                             class="bi bi-star-fill"
                                             viewBox="0 0 16 16">
                                            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                                        </svg>
                                    {% else %}
                                        <!-- 空星星 -->
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             width="16"
                                             height="16"
                                             fill="currentColor"
                                             class="bi bi-star"
                                             viewBox="0 0 16 16">
                                            <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                                        </svg>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endif %}
                        <div class="col-sm-1"></div>
                    </a>
                {% endfor %}
            {% else %}
                <p>暫無司機</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/app/index.html
{% extends 'base.html' %}
{% block content %}This is <em>bootstrap5</em> for <strong>Django</strong>.{% endblock %}

templates/app/nothing.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <div class="text-center container mt-5" style="padding-top: 250px">
      <img class="text-center" src="{% static 'image/nocar.png' %}" style='width:150px;'>
      <p>
      <h1>目前尚無訂單</h1>
    </div>
{% endblock %}

templates/app/price.html
{% extends 'base.html' %}
{% block title %}價格試算{% endblock %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% load widget_tweaks %}
    <div style="padding-top: 120px;padding-bottom: 50px;">
        <div class="container pt-5">
            <div class="row">
                <div class="col-sm-2 border-end">
                    <h2 class="text-center">
                        價格試算
                    </h1>
                    <label for="capacity">車資均分人數</label>
                    <input type="number" min="1" max="9" value="1" class="form-control" id="capacity" name="capacity"/>
                </div>
                <div class="col-sm-10">
                    <div class="container">
                        <h3 class="text-center">
                            <b>車資試算結果</b>
                        </h3>
                        {% if place_list %}
                            <table class="table table-bordered text-center">
                                <thead>
                                    <tr>
                                        <th scope="col">上車地點↓</th>
                                        {% for place in place_list|dictsort:"name"|slice:":5" %}
                                            <th scope="col">{{ place.name }}</th>
                                        {% endfor %}
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for place in place_list|dictsort:"name"|slice:"1:" %}
                                        <tr>
                                            <th scope="row">{{ place.name }}</th>
                                            {% for carfare in place.departure_fares.all|dictsort:"arrival.name" %}
                                                {% if forloop.counter <= forloop.parentloop.counter %}<td class="fare" data-fare="{{ carfare.fare }}"></td>{% endif %}
                                            {% endfor %}
                                        </tr>
                                    {% endfor %}
                                    <tr>
                                        <td colspan="7">單位:元/人</td>
                                    </tr>
                                </tbody>
                            </table>
                        {% else %}
                            <p>There are no carfare in the database.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/price.js' %}"></script>
{% endblock %}