se_bubuchacha/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

urls.py
from django.views.generic import TemplateView
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path("", views.CarpoolListView.as_view(), name="index"),
    path(
        "student/signup_and_login",
        views.StudentSignUpAndLoginView.as_view(),
        name="signup_and_login_student",
    ),
    path(
        "driver/signup_and_login",
        views.DriverSignUpAndLoginView.as_view(),
        name="signup_and_login_driver",
    ),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path(
        "password_change/",
        views.MyPasswordChangeView.as_view(),
        name="password_change",
    ),
    path("aboutus/", views.aboutus_view, name="aboutus"),
    path("carpools/", views.CarpoolListView.as_view(), name="carpools"),
    path("carpool_list_region/", views.carpool_list_region, name="carpools_region"),
    path(
        "carpool/history/",
        views.CarpoolHistoryListView.as_view(),
        name="carpool_history",
    ),
    path("carpool/create/", views.carpool_create, name="carpool_create"),
    path("carpool/<int:pk>", views.CarpoolDetailView.as_view(), name="carpool-detail"),
    path(
        "carpool/change_status/<int:pk>",
        views.carpool_change_status_view,
        name="carpool_change_status",
    ),
    path(
        "carpool/update_status/<int:pk>",
        views.carpool_update_status_view,
        name="carpool_update_status",
    ),
    path("price/", views.PriceView.as_view(), name="price"),
    path("drivers/", views.DriverListView.as_view(), name="drivers"),
    path("driver/<int:pk>", views.DriverReviewView.as_view(), name="driver_detail"),
    path("comment/delete/<int:pk>", views.delete_comment_view, name="delete_comment"),
    path("comment/edit/<int:pk>", views.edit_comment_view, name="edit_comment"),
    path("comment/create/", views.CommentCreateView.as_view(), name="comment_create"),
    path(
        "nothing/",
        TemplateView.as_view(template_name="app/nothing.html"),
        name="nothing",
    ),
]

templates/app/htmx/carpool_change_status.html
{% if carpool.status == 'w' %}
  <button hx-patch="{% url 'app:carpool_change_status' pk=carpool.pk %}"
          hx-target="#carpool-change-status"
          hx-swap="innerHTMl"
          class="btn btn-outline-dark"
          style="width:180px">出發</button>
{% elif carpool.status == 'd' %}
  <button hx-patch="{% url 'app:carpool_change_status' pk=carpool.pk %}"
          hx-target="#carpool-change-status"
          hx-swap="innerHTMl"
          class="btn btn-outline-dark"
          style="width:180px">抵達</button>
{% else %}
  <button disabled
          class="btn btn-outline-dark"
          style="width:180px">已抵達</button>
{% endif %}

templates/app/htmx/create_comment.html
<div id="main" hx-swap-oob="true">
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    {% load widget_tweaks %}
    <link rel="stylesheet" href="{% static 'css/star.css' %}">
    <div style="padding-bottom: 50px;">
        <div class="container mt-5">
            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col-sm-6 border shadow rounded p-5">
                    <form action="{% url 'app:comment_create' %}" method="post" id="form">
                        {% csrf_token %}
                        <div class="row">
                            <h3 class="text-center">
                                <b>填寫評論</b>
                            </h3>
                        </div>
                        <br>
                        <div class="form-group row">
                            <div class="col-auto">
                                <label for="Name" class="col-form-label">司機：</label>
                            </div>
                            <div class="col-auto">
                                <input type="text"
                                       readonly=""
                                       class="form-control-plaintext"
                                       value="{{ driver.profile.name }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-auto">
                                <label class="col-form-label">評分：</label>
                            </div>
                            <div class="col-auto">
                                <div class="rating">
                                    <input type="radio" id="star5" name="rating" value="5" hidden checked/>
                                    <label for="star5"></label>
                                    <input type="radio" id="star4" name="rating" value="4" hidden/>
                                    <label for="star4"></label>
                                    <input type="radio" id="star3" name="rating" value="3" hidden/>
                                    <label for="star3"></label>
                                    <input type="radio" id="star2" name="rating" value="2" hidden/>
                                    <label for="star2"></label>
                                    <input type="radio" id="star1" name="rating" value="1" hidden/>
                                    <label for="star1"></label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-md-12">
                            <label for="comment" class="col-form-label">評論：</label>
                            {% render_field form.content class="form-control" rows="3" %}
                            {% render_field form.score class="score" style="display:none" %}
                        </div>
                        <div align="center" class="mt-3">
                            <button type="submit" class="btn btn-secondary">送出</button>
                        </div>
                    </form>
                </div>
                <div class="col-sm-3"></div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/create_comment.js' %}"></script>
{% endblock %}
</div>